---
format: html
editor: source
toc: false
---

# Presentación {.unnumbered}

La Encuesta del [Núcleo Milenio en Política Laboral y Vida Familiar y Colectiva (LABOFAM)](https://labofam.cl/) tiene por objetivo central estudiar qué efectos laborales, familiares y políticos tienen las leyes recientemente implementadas para facilitar la conciliación entre trabajo, vida personal y familiar. Se seleccionaron al azar 2.000 personas que trabajaran en grandes empresas privadas en las regiones de Valparaíso, Metropolitana y Maule.

Los investigadores responsables de este estudio son el [Dr. Pablo Pérez Ahumada](https://labofam.cl/2025/06/05/pablo-perez-ahumada/), y la [Dra. Julieta Palma Palma](https://labofam.cl/2025/06/05/julieta-palma/), ambos del Departamento de Sociología de la Universidad de Chile [(FACSO-UCH)](https://facso.uchile.cl/). La investigación es patrocinada por la Agencia Nacional de Investigación y Desarrollo (ANID), del Gobierno de Chile, a través de la Iniciativa Milenio 2024.

La recolección de datos ha sido realizada mediante la plataforma abierta [formr.org](https://formr.org).

Este proyecto también han participado:

- Pablo Pérez-Ahumada

- Julieta Palma

- Daniela Olivares-Collío

- Teresa Barrera

- Kevin Carrasco

- M. Constanza Ayala
